"""Resume -> standalone HTML, the HTML->PDF-service twin of render.py's Typst path.

Both renderers consume the same `Resume` and must agree on layout: see
`templates/typist.typ` for the authoritative geometry (per-section entry
shapes, the density -> spacing `lerp`, the header rules). This module mirrors
that spec in CSS instead of Typst markup.

Unlike the Typst path, every string here is genuinely untrusted: Typst source
is generated by json-encoding the resume and handing it to `json()` inside the
template, so no resume text ever touches Typst *syntax*. HTML has no such
boundary — text and markup share one channel — so every interpolated value
MUST go through `_esc()` (`html.escape(..., quote=True)`). The one exception
is markup we author ourselves (tags, the " | " / "&middot;" separators).

Output is one self-contained document: a single inlined <style> block, a
system/CTS serif stack (no @font-face, no CDN), no <script>, no <img>. It is
POSTed to a headless-Chromium print-to-PDF service and must render identically
offline.
"""

from __future__ import annotations

import html
from collections.abc import Sequence

from .models import Contact, Entry, Resume

# --------------------------------------------------------------------------
# Escaping / trimming helpers
# --------------------------------------------------------------------------


def _esc(value: str) -> str:
    """The one and only path from resume text to HTML output.

    `quote=True` also escapes `"` so the same helper is safe to use inside
    attribute values (href="...") as well as element text.
    """
    return html.escape(value, quote=True)


def _clean(value: str) -> str:
    """Mirror Typst template's `get()`: trim, treat all-whitespace as empty."""
    return value.strip()


def _has(value: str) -> bool:
    return _clean(value) != ""


# --------------------------------------------------------------------------
# Density -> metrics (mirrors the `lerp` calls in typist.typ line for line)
# --------------------------------------------------------------------------


def _lerp(a: float, b: float, density: float) -> float:
    return a + (b - a) * density


class _Metrics:
    """Every density-dependent number, computed once per render.

    Values and ranges are copied verbatim from typist.typ's `#let ... = lerp(...)`
    block so the two renderers stay in lockstep if that file's tuning changes.
    """

    def __init__(self, density: float) -> None:
        d = density
        self.body_pt = _lerp(9.8, 8.6, d)
        # Typst's `leading` is *extra* space inserted between lines, not a
        # full line-height multiplier. CSS line-height is the full baseline-
        # to-baseline distance, so we approximate it as one em of glyph height
        # plus that leading, both in the same pt unit as body size. This is an
        # approximation (font metrics differ from exactly 1em) called out
        # again in the module docstring's "not reproducible" note.
        self.lead_pt = _lerp(0.60, 0.38, d) * self.body_pt
        self.line_height_pt = self.body_pt + self.lead_pt
        self.bullet_gap_pt = _lerp(2.4, 1.1, d)
        self.entry_gap_pt = _lerp(4.6, 1.8, d)
        self.section_gap_pt = _lerp(5.6, 2.2, d)
        self.side_margin_in = _lerp(0.44, 0.36, d)
        self.top_margin_in = _lerp(0.42, 0.28, d)
        self.bottom_margin_in = self.top_margin_in * 0.9
        self.name_pt = self.body_pt * 2.05
        self.heading_pt = self.body_pt * 1.18


def _num(value: float) -> str:
    """Trim a float to a short, stable decimal literal for CSS (e.g. 9.8, not 9.800000000001)."""
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text if text else "0"


# --------------------------------------------------------------------------
# CSS
# --------------------------------------------------------------------------

# Serif stack a headless-Chromium box will actually have installed, closest
# match to the Typst template's ("New Computer Modern", "Latin Modern Roman",
# "Times New Roman") ladder without shipping font files.
_FONT_STACK = '"Latin Modern Roman", "Computer Modern", "Times New Roman", Times, serif'


def _build_css(m: _Metrics) -> str:
    # pt/in units throughout, never px: this is a print document, and the
    # @page rule is what a Chromium print-to-PDF pass actually honors for
    # page geometry.
    return f"""
    @page {{
      size: Letter;
      margin: {_num(m.top_margin_in)}in {_num(m.side_margin_in)}in
              {_num(m.bottom_margin_in)}in {_num(m.side_margin_in)}in;
    }}
    * {{ box-sizing: border-box; }}
    html, body {{ margin: 0; padding: 0; }}
    body {{
      font-family: {_FONT_STACK};
      font-size: {_num(m.body_pt)}pt;
      line-height: {_num(m.line_height_pt)}pt;
      color: #000;
    }}
    a {{ color: inherit; text-decoration: underline; }}
    .header {{ text-align: center; }}
    .name {{
      font-size: {_num(m.name_pt)}pt;
      font-weight: bold;
    }}
    .contact, .tagline {{
      font-size: {_num(m.body_pt)}pt;
      margin-top: 2pt;
    }}
    .section {{
      margin-top: {_num(m.section_gap_pt)}pt;
    }}
    .section-title {{
      font-size: {_num(m.heading_pt)}pt;
      font-weight: bold;
      display: block;
    }}
    .section-rule {{
      border-bottom: 0.7pt solid #000;
      margin-top: 0.5pt;
    }}
    .entry {{
      margin-top: {_num(m.entry_gap_pt)}pt;
      /* An entry's header must never be orphaned from its own bullets, and an
         entry must not itself be split mid-way — both are ATS/readability
         requirements, not cosmetics. Both properties are set for browser
         coverage: `break-inside` is the current name, `page-break-inside` is
         the legacy alias some engines still key off for print. */
      page-break-inside: avoid;
      break-inside: avoid;
    }}
    .entry-row {{
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      gap: 6pt;
    }}
    .entry-row.secondary {{
      font-style: italic;
    }}
    .entry-left {{ text-align: left; }}
    .entry-right {{ text-align: right; white-space: nowrap; }}
    .entry-primary {{ font-weight: bold; }}
    .stack {{ font-style: italic; }}
    ul.bullets {{
      list-style: none;
      margin: {_num(m.bullet_gap_pt)}pt 0 0 0;
      padding: 0;
    }}
    ul.bullets li {{
      position: relative;
      padding-left: 11pt;
      margin-bottom: {_num(m.bullet_gap_pt)}pt;
    }}
    ul.bullets li:last-child {{ margin-bottom: 0; }}
    ul.bullets li::before {{
      content: "\\2022";
      position: absolute;
      left: 6pt;
    }}
    .skill-row {{
      margin: 1.5pt 0;
    }}
    """


# --------------------------------------------------------------------------
# Header
# --------------------------------------------------------------------------


def _contact_link(href_scheme: str, value: str) -> str:
    value = _clean(value)
    href = _esc(f"{href_scheme}{value}")
    return f'<a href="{href}">{_esc(value)}</a>'


def _header_html(resume: Resume) -> str:
    c: Contact = resume.contact
    parts: list[str] = []
    if _has(c.phone):
        parts.append(_esc(_clean(c.phone)))
    if _has(c.email):
        parts.append(_contact_link("mailto:", c.email))
    if _has(c.linkedin):
        parts.append(_contact_link("https://", c.linkedin))
    if _has(c.github):
        parts.append(_contact_link("https://", c.github))
    if _has(c.website):
        parts.append(_contact_link("https://", c.website))
    contact_line = " | ".join(parts)

    tagline = ""
    if _has(resume.target_role) or _has(resume.availability):
        chunks: list[str] = []
        if _has(resume.target_role):
            chunks.append(_esc(_clean(resume.target_role)))
        if _has(resume.availability):
            if _has(resume.target_role):
                chunks.append("&middot;")
            chunks.append(f"<b>Availability:</b> {_esc(_clean(resume.availability))}")
        tagline = f'<div class="tagline">{" ".join(chunks)}</div>'

    return (
        '<div class="header">'
        f'<div class="name">{_esc(_clean(c.name))}</div>'
        f'<div class="contact">{contact_line}</div>'
        f"{tagline}"
        "</div>"
    )


# --------------------------------------------------------------------------
# Section heading
# --------------------------------------------------------------------------


def _section_heading_html(title: str) -> str:
    return (
        '<div class="section">'
        f'<span class="section-title">{_esc(title)}</span>'
        '<div class="section-rule"></div>'
        "</div>"
    )


# --------------------------------------------------------------------------
# Bullets
# --------------------------------------------------------------------------


def _bullets_html(items: Sequence[str]) -> str:
    if not items:
        return ""
    lis = "".join(f"<li>{_esc(b)}</li>" for b in items)
    return f'<ul class="bullets">{lis}</ul>'


# --------------------------------------------------------------------------
# Entry shapes — the per-section geometry called out in the task, mirroring
# typist.typ's `entry2` / `entry1`.
# --------------------------------------------------------------------------


def _entry_two_line_html(
    primary: str,
    primary_meta: str,
    secondary: str,
    secondary_meta: str,
    bullets: Sequence[str],
) -> str:
    primary = _clean(primary)
    primary_meta = _clean(primary_meta)
    secondary = _clean(secondary)
    secondary_meta = _clean(secondary_meta)

    row1 = (
        '<div class="entry-row">'
        f'<span class="entry-left entry-primary">{_esc(primary)}</span>'
        f'<span class="entry-right">{_esc(primary_meta)}</span>'
        "</div>"
    )
    # Line 2 is omitted entirely (not just left blank) when both parts are
    # empty — e.g. a leadership entry with no `role` field set.
    row2 = ""
    if secondary != "" or secondary_meta != "":
        row2 = (
            '<div class="entry-row secondary">'
            f'<span class="entry-left">{_esc(secondary)}</span>'
            f'<span class="entry-right">{_esc(secondary_meta)}</span>'
            "</div>"
        )
    return f'<div class="entry">{row1}{row2}{_bullets_html(bullets)}</div>'


def _entry_one_line_html(name: str, stack: str, meta: str, bullets: Sequence[str]) -> str:
    name = _clean(name)
    stack = _clean(stack)
    meta = _clean(meta)

    left = f'<span class="entry-primary">{_esc(name)}</span>'
    if stack != "":
        left += f' | <span class="stack">{_esc(stack)}</span>'
    row = (
        '<div class="entry-row">'
        f'<span class="entry-left">{left}</span>'
        f'<span class="entry-right">{_esc(meta)}</span>'
        "</div>"
    )
    return f'<div class="entry">{row}{_bullets_html(bullets)}</div>'


# --------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------


def _education_section_html(resume: Resume) -> str:
    if not resume.education:
        return ""
    parts = [_section_heading_html(resume.education_title)]
    for e in resume.education:
        # Education: line1 = school (bold) | location (right); line2 = degree
        # (italic) | date (right) — location/date are swapped relative to
        # Work Experience on purpose, matching typist.typ's entry2 call.
        parts.append(_entry_two_line_html(e.org, e.location, e.role, e.date, e.bullets))
    return "".join(parts)


def _skills_section_html(resume: Resume) -> str:
    if not resume.skills:
        return ""
    parts = [_section_heading_html(resume.skills_title)]
    for g in resume.skills:
        label = _esc(_clean(g.label))
        items = _esc(_clean(g.items))
        parts.append(f'<div class="skill-row"><b>{label}:</b> {items}</div>')
    return "".join(parts)


def _role_entry_html(e: Entry, lead_with: str) -> str:
    # Work Experience / Leadership: line1 = employer (bold) | date (right);
    # line2 = title (italic) | location (right). `lead_with="role"` swaps only
    # the two LEFT slots (title <-> employer) — the right-hand column stays
    # date-then-location either way, per the task spec and typist.typ's
    # `role-entry`.
    top = e.role if lead_with == "role" else e.org
    bottom = e.org if lead_with == "role" else e.role
    return _entry_two_line_html(top, e.date, bottom, e.location, e.bullets)


def _experience_section_html(resume: Resume) -> str:
    if not resume.experience:
        return ""
    parts = [_section_heading_html(resume.experience_title)]
    for e in resume.experience:
        parts.append(_role_entry_html(e, resume.lead_with))
    return "".join(parts)


def _projects_section_html(resume: Resume) -> str:
    if not resume.projects:
        return ""
    parts = [_section_heading_html(resume.projects_title)]
    for e in resume.projects:
        # Projects: single line, no secondary row: bold role (project name),
        # then " | " + italic stack if stack is non-empty, date right-aligned.
        parts.append(_entry_one_line_html(e.role, e.stack, e.date, e.bullets))
    return "".join(parts)


def _leadership_section_html(resume: Resume) -> str:
    if not resume.leadership:
        return ""
    parts = [_section_heading_html(resume.leadership_title)]
    for e in resume.leadership:
        parts.append(_role_entry_html(e, resume.lead_with))
    return "".join(parts)


# --------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------


def render_html(resume: Resume, *, density: float = 0.0) -> str:
    """Render `resume` to a complete, standalone HTML document.

    Mirrors templates/typist.typ's layout (see that file for the geometry
    spec) so the same Resume renders visually equivalent whether it goes
    through Typst or an HTML->PDF service. All resume text is escaped via
    `_esc()`; the only unescaped strings in the output are markup literals
    this module writes itself.
    """
    m = _Metrics(density)
    css = _build_css(m)

    body_sections = "".join(
        [
            _header_html(resume),
            _education_section_html(resume),
            _skills_section_html(resume),
            _experience_section_html(resume),
            _projects_section_html(resume),
            _leadership_section_html(resume),
        ]
    )

    title = _esc(_clean(resume.contact.name)) or "Resume"
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        f"<title>{title} — Resume</title>\n"
        f"<style>{css}</style>\n"
        "</head>\n"
        f"<body>{body_sections}</body>\n"
        "</html>\n"
    )
